version: "3.9"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sasakitimaru
      POSTGRES_PASSWORD: sasaTa26
      POSTGRES_DB: sasakitiBlog
    restart: always
    networks:
      - lesson
networks:
  lesson:

# volumes:
#   udemy-postgres-data:

